### ISSUE TITLE
"Operation is not supported on this platform"

### ISSUE THREAD

**Issue by jd987** [imobile3/Loggr.Extensions.Logging#6]
Using version 1.0.0 on .Net Core 1.1 getting the following exception:

System.AggregateException: An error occurred while writing to logger(s). (Operation is not supported on this platform.) ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Loggr.LogClient.PostEventDelegate.BeginInvoke(Event eventObj, AsyncCallback callback, Object object)
   at Loggr.FluentEventBase`1.Post(Boolean Async)
   at Loggr.Extensions.Logging.LoggrLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.AspNetCore.Hosting.Internal.HostingLoggerExtensions.RequestStarting(ILogger logger, HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.CreateContext(IFeatureCollection contextFeatures)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
---> (Inner Exception #0) System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Loggr.LogClient.PostEventDelegate.BeginInvoke(Event eventObj, AsyncCallback callback, Object object)
   at Loggr.FluentEventBase`1.Post(Boolean Async)
   at Loggr.Extensions.Logging.LoggrLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
Microsoft.AspNetCore.Server.Kestrel:Warning: Connection processing ended abnormally

**Comment by withinfocus** [comment]
This should be resolved once we land #5.

**Comment by jd987** [comment]
Great!  I see there is a potential fix.  When are you anticipating a new release?
Thanks

**Comment by withinfocus** [comment]
Should be all set now. A v1.0.1 release is out on NuGet via #7.
